# This file contains values from Cookiecutter

default_context:
  project_name: "pygizmo"
  project_description: "Tools"
  organization: "Fabled Freedom"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "zpyoung"
  email: "zach@fabledfreedom.com"
  version: "0.1.0"
  line_length: "120"
  create_example_template: "none"
